import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {Provider} from "@/components/ui/provider"
import {StoreProvider} from "@/components/store";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "InvoicingCat - Free Invoice Generator",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <Provider>{children}</Provider>
            </body>
            </html>
        </StoreProvider>
    );
}
